server:
  port: 8088
  servlet:
    context-path: /api
    # session 30 ???
    session:
      timeout: "P30D"
      cookie:
        same-site: none
        secure: true
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/user-center
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: isDelete

